(function(){
const DEFAULT={
  version:1,
  quiz:{layout:'studio',scale:1,colors:{accent:'#7c5cff',accent2:'#5b8cff',text:'#eef0f6',panel:{background:'#10111a',opacity:.72,blur:10}},font:{family:'Inter',weight:700,size:18},radius:18,animation:{style:'fade',speed:.25},elements:{showVotePercent:true,showVoteBars:true,highlightCorrect:true}},
  leaderboard:{layout:'list',scale:1,colors:{accent:'#7c5cff',accent2:'#5b8cff',text:'#eef0f6',panel:{background:'#10111a',opacity:.78,blur:8}},font:{family:'Inter',weight:800,size:22},radius:16,animation:{style:'slide',speed:.25},elements:{showAvatars:true,rowsVisible:5}},
  timer:{layout:'ring',scale:1,colors:{accent:'#7c5cff',accent2:'#5b8cff',text:'#eef0f6',panel:{background:'#08090e',opacity:.55,blur:6}},font:{family:'JetBrains Mono',weight:700,size:28},radius:999,animation:{style:'fade',speed:.25},elements:{showLabel:true}}
};
const reduce=()=>window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;
function clone(v){return typeof structuredClone==='function'?structuredClone(v):JSON.parse(JSON.stringify(v))}
function isObj(v){return !!v&&typeof v==='object'&&!Array.isArray(v)}
function merge(a,b){ if(!isObj(b)) return clone(a); const o=isObj(a)?{...a}:{}; for(const k in b){ o[k]=isObj(a?.[k])&&isObj(b[k])?merge(a[k],b[k]):b[k]; } return o; }
function clamp(n,min,max){return Math.max(min,Math.min(max,Number(n)||0))}
function hexRgb(h){h=String(h||'#000').replace('#',''); if(h.length===3)h=h.split('').map(c=>c+c).join(''); const n=parseInt(h,16); return `${(n>>16)&255},${(n>>8)&255},${n&255}`}
function unwrapPayload(payload){ let p=payload; while(Array.isArray(p)&&p.length===1) p=p[0]; return p; }
function normTheme(t){return merge(DEFAULT,unwrapPayload(t)||{})}
function themeSig(t){try{return JSON.stringify(normTheme(t))}catch(e){return String(Date.now())}}
function setText(el,text){const v=String(text??''); if(el&&el.textContent!==v) el.textContent=v}
function child(parent,sel,tag='div',cls=''){let el=parent.querySelector(':scope > '+sel); if(!el){el=document.createElement(tag); if(cls) el.className=cls; parent.appendChild(el)} return el}
function applyVars(el,cfg,type){ const c=cfg.colors||{},p=c.panel||{}; el.style.setProperty('--qm-accent',c.accent||'#7c5cff'); el.style.setProperty('--qm-accent2',c.accent2||c.accent||'#5b8cff'); el.style.setProperty('--qm-text',c.text||'#eef0f6'); el.style.setProperty('--qm-panel-rgb',hexRgb(p.background||'#10111a')); el.style.setProperty('--qm-panel-opacity',p.opacity??.72); el.style.setProperty('--qm-blur',(p.blur??8)+'px'); el.style.setProperty('--qm-radius',(cfg.radius??16)+'px'); el.style.setProperty('--qm-font',cfg.font?.family||'Inter'); el.style.setProperty('--qm-weight',cfg.font?.weight||700); el.style.setProperty('--qm-size',(cfg.font?.size||16)); el.style.setProperty('--qm-speed',(cfg.animation?.speed??.25)+'s'); el.style.setProperty('--qm-scale',clamp(cfg.scale||1,.5,1.8)); el.style.setProperty('--qm-fit-x',el.style.getPropertyValue('--qm-fit-x')||'0px'); el.style.setProperty('--qm-fit-y',el.style.getPropertyValue('--qm-fit-y')||'0px'); el.dataset.anim=type==='timer'?'none':(cfg.animation?.style||'none'); el.dataset.layout=cfg.layout; el.dataset.overlay=type; el.style.left='50%'; el.style.top='50%'; el.style.transform='translate(-50%,-50%) translate(var(--qm-fit-x),var(--qm-fit-y)) scale(var(--qm-scale))'; }
function fitIntoFrame(el){requestAnimationFrame(()=>{const parent=el.parentElement||document.documentElement; const pr=parent.getBoundingClientRect(), r=el.getBoundingClientRect(); let dx=0,dy=0,pad=8; if(r.left<pr.left+pad) dx=pr.left+pad-r.left; if(r.right>pr.right-pad) dx=pr.right-pad-r.right; if(r.top<pr.top+pad) dy=pr.top+pad-r.top; if(r.bottom>pr.bottom-pad) dy=pr.bottom-pad-r.bottom; el.style.setProperty('--qm-fit-x',`${dx}px`); el.style.setProperty('--qm-fit-y',`${dy}px`);});}
function root(mount,type,cfg){const roots=[...mount.querySelectorAll(`:scope > .qm-overlay-root[data-overlay="${type}"]`)]; let wrap=roots[0]; roots.slice(1).forEach(el=>el.remove()); if(!wrap){wrap=document.createElement('div');wrap.className='qm-overlay-root';wrap.dataset.overlay=type;mount.appendChild(wrap); wrap._qmNew=true} applyVars(wrap,cfg,type); return wrap}
function enter(wrap,key){if(reduce()) return; if(wrap._qmEnterKey===key&&!wrap._qmNew) return; wrap._qmEnterKey=key; wrap._qmNew=false; wrap.classList.remove('qm-enter'); void wrap.offsetWidth; wrap.classList.add('qm-enter')}
async function loadTheme(){try{const r=await fetch('/api/overlay-theme?ts='+Date.now(),{cache:'no-store'}); if(r.ok){const j=await r.json(); return normTheme(j.theme||j)}}catch(e){} return normTheme()}
function emptyQuizData(){return {question_number:0,total_questions:0,question:'Waiting for the next quiz…',answers:[],votes:[],correct_index:null,reveal_answers:false}}
function sampleQuizData(){return {question_number:3,total_questions:10,question:'Which planet is the largest in our solar system?',answers:['Mercury','Jupiter','Saturn','Mars'],votes:[22,58,14,6],correct_index:1,reveal_answers:true}}
function quizData(d){return d||emptyQuizData()}
function forceCorrectVisual(row,isCorrect){ row.classList.toggle('correct',!!isCorrect); row.classList.toggle('is-correct',!!isCorrect); row.dataset.correct=isCorrect?'true':'false'; const props=['background','border-color','box-shadow','color','outline','transform']; props.forEach(p=>row.style.removeProperty(p)); if(isCorrect){ row.style.setProperty('background','linear-gradient(90deg, rgba(0,255,136,.42), rgba(124,92,255,.30))','important'); row.style.setProperty('border-color','var(--qm-accent2, #00ff88)','important'); row.style.setProperty('box-shadow','0 0 30px rgba(0,255,136,.85), inset 0 0 0 2px rgba(255,255,255,.16)','important'); row.style.setProperty('color','var(--qm-text, #ffffff)','important'); row.style.setProperty('outline','3px solid rgba(0,255,136,.72)','important'); row.style.setProperty('transform','scale(1.02)','important'); } }
function renderQuiz(mount,theme,data){const cfg=normTheme(theme).quiz,d=quizData(data),els=cfg.elements||{},wrap=root(mount,'quiz',cfg); let sec=wrap.querySelector(':scope > .qm-quiz'); if(!sec){sec=document.createElement('section'); wrap.replaceChildren(sec)} sec.className=`qm-quiz qm-${cfg.layout}`; setText(child(sec,'p','p'),d.question_number?`Question ${d.question_number}${d.total_questions?' / '+d.total_questions:''}`:'Quiz idle'); setText(child(sec,'h2','h2'),d.question||'Get Ready!'); const list=child(sec,'.qm-answer-list','div','qm-answer-list'),answers=d.answers||[],votes=d.votes||[0,0,0,0],letters='ABCD',reveal=!!(d.reveal_answers||d.show_answers||d.show_correct),correctIndex=Number(d.correct_index),hasCorrect=Number.isFinite(correctIndex)&&correctIndex>=0; while(list.children.length>answers.length) list.lastChild.remove(); answers.forEach((a,i)=>{let row=list.children[i]; if(!row){row=document.createElement('div'); row.innerHTML='<span class="qm-vbar"></span><b></b><span class="qm-answer-text"></span><em></em>'; list.appendChild(row)} const isCorrect=reveal&&hasCorrect&&i===correctIndex; row.className=`qm-ans${isCorrect?' correct is-correct':''}`; forceCorrectVisual(row,isCorrect); const bar=row.querySelector('.qm-vbar'); bar.hidden=els.showVoteBars===false; bar.style.width=`${votes[i]||0}%`; setText(row.querySelector('b'),letters[i]||i+1); setText(row.querySelector('.qm-answer-text'),a); const pct=row.querySelector('em'); pct.hidden=els.showVotePercent===false; setText(pct,`${votes[i]||0}%`)}); enter(wrap,`quiz:${d.question_number||''}:${d.question||''}:${reveal?'revealed':'hidden'}:${hasCorrect?correctIndex:'none'}`); fitIntoFrame(wrap)}
function normalizeEntry(e){return {user_id:e?.user_id||e?.id||e?.unique_id||'',username:e?.username||e?.display_name||e?.name||'User',name:e?.name||e?.display_name||e?.username||'User',score:Number(e?.score||0),avatar_url:e?.avatar_url||e?.avatar||e?.profilePictureUrl||e?.profile_picture_url||'',correct:Number(e?.correct||e?.correct_answers||0),incorrect:Number(e?.incorrect||e?.incorrect_answers||0),streak:Number(e?.streak||0)}}
function normalizeRows(data,cfg){return (Array.isArray(data)?data:(data?.entries||data?.leaderboard||[])).map(normalizeEntry).sort((a,b)=>b.score-a.score).slice(0,cfg.elements?.rowsVisible||5)}
function initials(e){return String(e.username||e.name||'U').replace('@','').trim().slice(0,2).toUpperCase()||'U'}
function avatarEl(e,show){if(!show) return document.createComment('avatar-hidden'); const av=document.createElement('span'); av.className='qm-av'; const url=e.avatar_url; if(url){const img=document.createElement('img'); img.src=url; img.alt=''; img.referrerPolicy='no-referrer'; img.onerror=()=>{img.remove(); setText(av,initials(e)); av.classList.add('fallback')}; av.appendChild(img)} else {setText(av,initials(e)); av.classList.add('fallback')} return av}
function makeRow(e,rank,cfg){const row=document.createElement('div'); row.className=`qm-lrow top${rank}`; const r=document.createElement('b'); setText(r,rank); const name=document.createElement('span'); name.className='qm-name'; setText(name,e.username||e.name||'User'); const score=document.createElement('em'); setText(score,e.score||0); row.append(r,avatarEl(e,cfg.elements?.showAvatars!==false),name,score); return row}
function renderList(sec,rows,cfg){const h=document.createElement('h2'); const title=document.createElement('span'); const live=document.createElement('small'); setText(title,cfg.layout==='ticker'?'Top players':'Leaderboard'); setText(live,'Live'); h.append(title,live); sec.appendChild(h); rows.forEach((e,i)=>sec.appendChild(makeRow(e,i+1,cfg)))}
function renderPodium(sec,rows,cfg){const bars=document.createElement('div'); bars.className='qm-podium-bars'; const top=[rows[1],rows[0],rows[2]].filter(Boolean); top.forEach((e,i)=>{const col=document.createElement('div'); col.className=`qm-pcol p${i}`; const av=avatarEl(e,cfg.elements?.showAvatars!==false); const name=document.createElement('strong'); const score=document.createElement('small'); const rank=document.createElement('i'); setText(name,e.username||e.name||'User'); setText(score,e.score||0); setText(rank,i===1?1:i===0?2:3); col.append(av,name,score,rank); bars.appendChild(col)}); sec.appendChild(bars); rows.slice(3).forEach((e,i)=>sec.appendChild(makeRow(e,i+4,cfg)))}
function renderLeaderboard(mount,theme,data){const cfg=normTheme(theme).leaderboard,rows=normalizeRows(data,cfg),wrap=root(mount,'leaderboard',cfg); const sec=document.createElement('section'); sec.className=`qm-lb qm-${cfg.layout}`; if(cfg.layout==='podium') renderPodium(sec,rows,cfg); else renderList(sec,rows,cfg); wrap.replaceChildren(sec); enter(wrap,`leaderboard:${cfg.layout}:${rows.map(r=>`${r.user_id||r.username}:${r.score}`).join('|')}`); fitIntoFrame(wrap)}
function timerData(data){const d=data&&typeof data==='object'?data:{}; const total=Number(d.total??d.duration??d.seconds??30)||30; const raw=d.remaining??d.time_remaining??d.seconds_left??d.left??0; return {remaining:Math.max(0,Number(raw)||0),total,label:d.label||''};}
function renderTimer(mount,theme,data){const cfg=normTheme(theme).timer,d=timerData(data),wrap=root(mount,'timer',cfg),pct=Math.max(0,Math.min(1,d.remaining/(d.total||30))); let sec=wrap.querySelector(':scope > .qm-timer'); if(!sec){sec=document.createElement('section'); wrap.replaceChildren(sec)} sec.className=`qm-timer qm-${cfg.layout}`; const idle=d.remaining<=0; const secs=Math.ceil(d.remaining); const mins=Math.floor(secs/60); const time=idle?'Idle':`${mins}:${String(secs%60).padStart(2,'0')}`; if(cfg.layout==='bar'){sec.replaceChildren(child(sec,'div','div'),child(sec,'i','i')); const div=sec.querySelector('div'); setText(child(div,'b','b'),cfg.elements?.showLabel!==false?(idle?'Timer ready':'Time remaining'):''); setText(child(div,'em','em'),time); const i=sec.querySelector('i'); let span=i.querySelector('span'); if(!span){span=document.createElement('span'); i.appendChild(span)} span.style.transform=`scaleX(${pct})`} else if(cfg.layout==='pill'){sec.replaceChildren(child(sec,'i','i'),child(sec,'b','b'),child(sec,'span','span')); setText(sec.querySelector('i'),'⏱'); setText(sec.querySelector('b'),time); const s=sec.querySelector('span'); s.hidden=cfg.elements?.showLabel===false; setText(s,idle?'ready':'left')} else {if(!sec.querySelector('svg')) sec.innerHTML='<svg viewBox="0 0 128 128"><circle cx="64" cy="64" r="56"></circle><circle cx="64" cy="64" r="56"></circle></svg><div><b></b><span></span></div>'; sec.querySelector('circle+circle').style.strokeDashoffset=352*(1-pct); setText(sec.querySelector('b'),idle?'--':Math.ceil(d.remaining)); const s=sec.querySelector('span'); s.hidden=cfg.elements?.showLabel===false; setText(s,idle?'ready':'seconds')} }
function themeFromPayload(payload){const p=unwrapPayload(payload); return normTheme(p?.theme||p);}
function onThemeUpdate(client,handler){let last=''; let timer=null; const apply=(payload)=>{const next=themeFromPayload(payload); const sig=themeSig(next); if(sig===last) return; last=sig; handler(next)}; if(client?.on){client.on('overlay_theme_updated',apply); client.on('signal:overlay_theme_updated',apply); client.on('ready',()=>loadTheme().then(apply)); client.on('ws_open',()=>loadTheme().then(apply)); client.on('ws_reconnect',()=>loadTheme().then(apply));} window.addEventListener('storage',(event)=>{if(event.key==='overlay_theme') loadTheme().then(apply);}); window.addEventListener('overlay_theme_updated',(event)=>apply(event.detail)); loadTheme().then(apply); timer=setInterval(()=>loadTheme().then(apply).catch(()=>{}),2000); window.addEventListener('beforeunload',()=>{if(timer) clearInterval(timer)}); return apply;}
window.OverlayTheme={DEFAULT,normTheme,loadTheme,sampleQuizData,onThemeUpdate,renderQuiz,renderLeaderboard,renderTimer,render(type,mount,theme,data){ if(type==='leaderboard')return renderLeaderboard(mount,theme,data); if(type==='timer')return renderTimer(mount,theme,data); return renderQuiz(mount,theme,data); }};
})();
