"""Generate a Python module containing compressed frontend assets.

This prevents HTML/CSS/JS/frontend asset files from being installed as loose,
readable files under Program Files. The generated module is intentionally not
committed; build_quizmaster.ps1 recreates it before PyInstaller runs.
"""

from __future__ import annotations

import base64
import json
import mimetypes
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "core" / "resources"
OUT_FILE = OUT_DIR / "web_assets_bundle.py"

ASSET_ROOTS = [
    ROOT / "core" / "assets",
    ROOT / "core" / "server" / "static",
    ROOT / "core" / "server" / "themes",
    ROOT / "core" / "server" / "overlays",
    ROOT / "core" / "quiz" / "html",
    ROOT / "core" / "quiz" / "css",
    ROOT / "core" / "quiz" / "js",
]

# NOTE: audio (.mp3/.wav/.ogg) is deliberately NOT embedded here. The desktop
# app plays sounds via QMediaPlayer from files, not over HTTP to the browser
# sources. Embedding a multi-MB .wav as a base64 string in this generated module
# produces a huge string literal that breaks the Nuitka/MSVC compile of the
# bundle, which then makes every embedded widget HTML "not found". Sounds are
# shipped as loose data files instead (see build_quizmaster_nuitka.ps1).
INCLUDE_SUFFIXES = {
    ".html", ".htm", ".css", ".js", ".mjs", ".json", ".svg",
    ".png", ".jpg", ".jpeg", ".gif", ".webp", ".ico",
    ".woff", ".woff2", ".ttf", ".otf",
}


def rel_key(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def main() -> None:
    assets: dict[str, dict[str, str]] = {}
    for root in ASSET_ROOTS:
        if not root.exists():
            continue
        for path in root.rglob("*"):
            if not path.is_file() or path.suffix.lower() not in INCLUDE_SUFFIXES:
                continue
            raw = path.read_bytes()
            key = rel_key(path)
            assets[key] = {
                "media_type": mimetypes.guess_type(path.name)[0] or "application/octet-stream",
                "data": base64.b64encode(zlib.compress(raw, level=9)).decode("ascii"),
            }

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUT_DIR / "__init__.py").touch()
    payload = json.dumps(assets, sort_keys=True, separators=(",", ":"))
    OUT_FILE.write_text(
        "# Auto-generated by scripts/generate_web_assets_bundle.py. Do not edit or commit.\n"
        f"ASSETS = {payload}\n",
        encoding="utf-8",
    )
    print(f"Embedded web assets written: {OUT_FILE} ({len(assets)} files)")


if __name__ == "__main__":
    main()
